# Generated by Django 3.0.8 on 2020-07-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0004_auto_20200719_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='problem_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_code', models.IntegerField()),
                ('problem', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='question_code',
            field=models.IntegerField(default=3950),
        ),
    ]
