# Generated by Django 3.0.8 on 2020-07-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0006_auto_20200720_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='problem',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='problem_table',
        ),
    ]
