# Generated by Django 3.0.8 on 2020-07-20 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0007_auto_20200720_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='question_code',
            field=models.IntegerField(default=3950, unique=True),
        ),
    ]
