# Generated by Django 3.0.8 on 2020-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0008_auto_20200720_1855'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='constraints',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='questions',
            name='sample_input',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='questions',
            name='sample_output',
            field=models.TextField(default=None),
        ),
    ]
