# Generated by Django 3.0.8 on 2020-07-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0009_auto_20200723_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='constraints',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='problem',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='sample_input',
            field=models.TextField(default='null'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='sample_output',
            field=models.TextField(default='null'),
        ),
    ]
