# Generated by Django 3.0.8 on 2020-07-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0011_auto_20200723_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='input_format',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='questions',
            name='output_format',
            field=models.TextField(default=None),
        ),
    ]
