# Generated by Django 3.0.8 on 2020-07-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0012_auto_20200723_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='test_cases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_code', models.IntegerField(unique=True)),
                ('test_case_inputs', models.TextField()),
                ('test_case_outputs', models.TextField()),
            ],
        ),
    ]
