# Generated by Django 3.0.8 on 2020-07-27 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0014_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='skills',
        ),
        migrations.AlterField(
            model_name='profile',
            name='education',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
