# Generated by Django 3.0.8 on 2020-07-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0016_auto_20200727_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='skill',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='education',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(default='null', upload_to='profile_pics'),
        ),
    ]
