# Generated by Django 3.0.8 on 2020-07-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0017_auto_20200727_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_username',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
