# Generated by Django 3.0.8 on 2020-07-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0018_auto_20200727_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='id',
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
