# Generated by Django 3.0.8 on 2020-07-27 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0019_auto_20200727_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='education',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='skill',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
