# Generated by Django 3.0.8 on 2020-07-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0021_auto_20200727_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='profile_pics'),
        ),
    ]
