# Generated by Django 3.0.8 on 2020-07-27 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0023_auto_20200727_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='facebook',
        ),
    ]
