# Generated by Django 3.0.8 on 2020-07-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0024_remove_user_profile_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='facebook',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='github',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='linkedin',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='stackoverflow',
            field=models.TextField(default=None, null=True),
        ),
    ]
