# Generated by Django 3.0.8 on 2020-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0025_auto_20200727_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='facebook',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='github',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='linkedin',
            field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='stackoverflow',
            field=models.TextField(default=None),
        ),
    ]
