# Generated by Django 3.0.8 on 2020-07-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0027_auto_20200727_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='stackoverflow',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='twiter',
            field=models.TextField(default='add link', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='facebook',
            field=models.TextField(default='add link', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='github',
            field=models.TextField(default='add link', null=True),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='linkedin',
            field=models.TextField(default='add link', null=True),
        ),
    ]
