# Generated by Django 3.0.8 on 2020-07-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0028_auto_20200727_1921'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='mobile',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user_profile',
            name='whatsapp',
            field=models.IntegerField(default=0),
        ),
    ]
