# Generated by Django 3.0.8 on 2020-07-29 04:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0032_auto_20200729_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_cases',
            name='ts_in_out',
        ),
        migrations.AddField(
            model_name='test_cases',
            name='ts_out',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=9),
        ),
    ]
