# Generated by Django 3.0.8 on 2020-07-29 04:26

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0033_auto_20200729_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='test_cases',
            name='ts_in',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=2),
        ),
    ]
