# Generated by Django 3.0.8 on 2020-07-29 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0034_test_cases_ts_in'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_cases',
            name='ts_in',
        ),
        migrations.RemoveField(
            model_name='test_cases',
            name='ts_out',
        ),
    ]
