# Generated by Django 3.0.8 on 2020-07-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0035_auto_20200729_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='ctc',
            field=models.CharField(default='Best in Industry', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='job_role',
            field=models.CharField(default='not mentioned', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='type_algo',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='yop',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
