# Generated by Django 3.0.8 on 2020-07-29 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0036_auto_20200729_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
