# Generated by Django 3.0.8 on 2020-07-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0037_challenges_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='format',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='location',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='openings',
            field=models.TextField(null=True),
        ),
    ]
