# Generated by Django 3.0.8 on 2020-07-29 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pycode', '0038_auto_20200729_1341'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenges',
            name='exam_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='challenges',
            name='ques_code',
            field=models.TextField(null=True),
        ),
    ]
